marked.js実装
KorRyu3/TriPal pull request #25
Opened 2024-01-24 19:05 UTC by nka21

marked.js実装
markdown デザイン上手くいかないので要調整

2024-01-25 00:28 UTC, KorRyu3 commented
確認間に合わないからさすがに今日は無理かも

2024-01-25 00:45 UTC, KorRyu3 requested changes
取り敢えず今見れる箇所だけレビューしといた。

変更箇所が多々あるので確認よろしくね

2024-01-25 00:45 UTC, KorRyu3 commented on src/tripalgpt.py
> +                verbose=True  # 途中経過を表示(debug用)
ここはコメントアウトしておいてください

2024-01-25 00:45 UTC, KorRyu3 commented on src/static/index.js
> +      marked.parse(streaming);
ここはブラウザの負荷分散のために、もっといい方法があるだろうね。

今のところ、トークンが来る度に毎回レンダリングしてるから重くなりそう。

マージする前に要検討かな

2024-01-25 00:45 UTC, KorRyu3 commented on src/static/index.js
> +const ws = new WebSocket("ws://" + web_url + "/chat");
ここら辺のWebSocket周りは、次のように修正をお願いします。

```js
/*
デプロイ用WebSocket
PRするときは、下のデバッグ用をコメントアウトし、こっちを有効化してください。
*/
const web_url = "tripal-ca.greenbay-9762fead.japaneast.azurecontainerapps.io"
const ws = new WebSocket("wss://" + web_url + "/chat");

/*
デバッグ用WebSocket
開発する時は、こっちのWebSocketを使ってください。
PRする時は、コメントアウトすること
*/
// const web_url = "0.0.0.0:8000";
// const ws = new WebSocket("ws://" + web_url + "/chat");
```

2024-01-25 00:45 UTC, KorRyu3 commented on src/templates/index.html
> +    />
ここのCSSの順番ってこれでいいんかな。

2024-01-25 00:45 UTC, KorRyu3 commented on src/static/index.js
> +      marked.parse(streaming);
ここはブラウザの負荷分散のために、もっといい方法があるだろうね。

今のところ、トークンが来る度に毎回レンダリングしてるから重くなりそう。

マージする前に要検討かな

2024-02-02 12:51 UTC, nka21 commented on src/templates/index.html
> +    />
下に書いてあるのは、reset.cssでもないから、これが正しいと思うよ
fontawesomeで読み込んで使ってるのは、送信ボタンの矢印やから、この順番で合ってると思う

2024-02-02 14:11 UTC, nka21 commented on src/static/index.js
> +      marked.parse(streaming);
んー、実害が出るほどの負荷はないから、問題ないんじゃない。
とりあえず、優先順位は低い

2024-02-03 06:40 UTC, KorRyu3 commented on src/static/index.js
> +      marked.parse(streaming);
今のプログラムっtoken来るたびにinnerHTMLにぶち込むんじゃないんだっけか。
なんか変えたんだっけ？

2024-02-03 07:21 UTC, KorRyu3 requested changes
バックエンドについての注意点と、自動スクロールとliタグの不具合

2024-02-03 07:21 UTC, KorRyu3 commented on src/static/index.js
> +};
ここの「下までスクロールする」は、LLMの応答が来たら自動的に下までスクロールするってことだよね。

https://github.com/KorRyu3/TriPal/assets/146335193/5f6687e1-f45d-4778-8bc3-b4f02b6f5a4a


今のところ、**一瞬だけ下に下がってそれ以降はスクロールしない**、って挙動になってるよ

2024-02-03 07:21 UTC, KorRyu3 commented on src/static/style.css
# liタグのマーカーの挙動がおかしい。

点がつく時とつかない時がある。
- ←これ

個人的には点とかが付いてた方が見やすくて好き

olの中にulがあるときは点が出て、div直下にulがある時は出ない？


## div > ol > li > ul > li
点がつく
<img width="1067" alt="スクリーンショット 2024-02-03 16 17 14" src="https://github.com/KorRyu3/TriPal/assets/146335193/30b712d3-47e3-416d-a4aa-9a71d911b76e">


## div > ul > li
点がつかない
<img width="1017" alt="スクリーンショット 2024-02-03 16 12 55" src="https://github.com/KorRyu3/TriPal/assets/146335193/a4900df8-8b42-4aa3-aedf-f853bb356f1d">

2024-02-03 07:33 UTC, KorRyu3 commented
# marked.jsの挙動・デザインまとめ。
タグがネストになってるとまた話は変わるかも。
デザイン調整のために、一応見ておいてね。

<img width="719" alt="スクリーンショット 2024-02-03 15 33 22" src="https://github.com/KorRyu3/TriPal/assets/146335193/9d347367-32c8-4069-9a88-70279da1d6c0">
<img width="715" alt="スクリーンショット 2024-02-03 15 33 27" src="https://github.com/KorRyu3/TriPal/assets/146335193/665d5a98-bc71-461c-9e7b-fdc9e33f7570">
<img width="706" alt="スクリーンショット 2024-02-03 15 33 30" src="https://github.com/KorRyu3/TriPal/assets/146335193/15fad82c-4797-4eff-8df9-096121df9ab8">
<img width="712" alt="スクリーンショット 2024-02-03 15 33 35" src="https://github.com/KorRyu3/TriPal/assets/146335193/517c3ff2-bc36-4fee-a4b8-1633a3112bd8">
<img width="713" alt="スクリーンショット 2024-02-03 15 34 01" src="https://github.com/KorRyu3/TriPal/assets/146335193/38ac14d8-17e2-4aef-83b2-cee23daf6ea8">
<img width="706" alt="スクリーンショット 2024-02-03 15 34 05" src="https://github.com/KorRyu3/TriPal/assets/146335193/681b66b2-dc0a-476b-a82d-c0ca408a092b">
<img width="718" alt="スクリーンショット 2024-02-03 15 34 09" src="https://github.com/KorRyu3/TriPal/assets/146335193/fbb6ce4a-fb15-431c-8539-9ca0c2bda858">
<img width="708" alt="スクリーンショット 2024-02-03 15 36 24" src="https://github.com/KorRyu3/TriPal/assets/146335193/c3cf335a-fe15-4789-a719-467457fc8044">

2024-02-03 08:00 UTC, KorRyu3 commented
あと、個人的には各要素の間(行間？)はもっとスペース開けていいと思うよ。
ちょっとギチってるのが気になるかな

<img width="1084" alt="スクリーンショット 2024-02-03 16 59 21" src="https://github.com/KorRyu3/TriPal/assets/146335193/b2fc2ea4-38f9-41fe-b934-6872d45da275">

2024-02-03 14:54 UTC, nka21 commented
デバッグしてたら、急にタイムアウトしたのでメモ

```
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 196, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 138, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1212, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
    async for part in self._httpcore_stream:
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
    raise exc
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 357, in handle
    await self.app(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 92, in app
    await func(session)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 360, in app
    await dependant.call(**values)
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/src/app.py", line 50, in chat
    async for output in tripal_gpt.get_async_generator_output(user_input=user_chat):
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/src/tripalgpt.py", line 202, in get_async_generator_output
    async for res in generator_response:
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 737, in astream_log
    await task
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 691, in consume_astream
    async for chunk in self.astream(input, config, **kwargs):
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1472, in astream
    async for step in iterator:
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 240, in __aiter__
    async for chunk in self.agent_executor._aiter_next_step(
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1192, in _aiter_next_step
    output = await self.agent.aplan(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 409, in aplan
    output = await self.runnable.ainvoke(inputs, config={"callbacks": callbacks})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1747,  [...]

2024-02-03 15:51 UTC, KorRyu3 commented
> デバッグしてたら、急にタイムアウトしたのでメモ
> 
> ```
> ConnectionResetError: [Errno 54] Connection reset by peer
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
>     yield
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
>     return await self._stream.receive(max_bytes=max_bytes)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 196, in receive
>     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/anyio/streams/tls.py", line 138, in _call_sslobject_method
>     data = await self.transport_stream.receive()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1212, in receive
>     raise self._protocol.exception
> anyio.BrokenResourceError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
>     yield
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 252, in __aiter__
>     async for part in self._httpcore_stream:
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
>     async for part in self._stream:
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
>     raise exc
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
>     async for chunk in self._connection._receive_response_body(**kwargs):
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
>     event = await self._receive_event(timeout=timeout)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
>     data = await self._network_stream.read(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
>     with map_exceptions(exc_map):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ReadError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
>     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
>     await self.app(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
>     raise exc
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
>     await app(scope, receive, sender)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
>     await route.handle(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 357, in handle
>     await self.app(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
>     await wrap_app_handling_exceptions(app, session)(scope, receive, send)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
>     raise exc
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
>     await app(scope, receive, sender)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/starlette/routing.py", line 92, in app
>     await func(session)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 360, in app
>     await dependant.call(**values)
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/src/app.py", line 50, in chat
>     async for output in tripal_gpt.get_async_generator_output(user_input=user_chat):
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/src/tripalgpt.py", line 202, in get_async_generator_output
>     async for res in generator_response:
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 737, in astream_log
>     await task
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 691, in consume_astream
>     async for chunk in self.astream(input, config, **kwargs):
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1472, in astream
>     async for step in iterator:
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 240, in __aiter__
>     async for chunk in self.agent_executor._aiter_next_step(
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1192, in _aiter_next_step
>     output = await self.agent.aplan(
>              ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kojimanaoki/Documents/GitHub/TriPal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 409, in aplan
>     output = await self.runnable.ainvoke(inputs, config={"callbacks": callbacks})
>          [...]

2024-02-03 15:52 UTC, KorRyu3 commented
間違えてcloseしちゃった、焦った...

2024-02-07 15:17 UTC, nka21 commented on src/static/style.css
`できた`

2024-02-07 15:18 UTC, nka21 commented on src/static/index.js
> +      marked.parse(streaming);
できた

2024-02-09 10:03 UTC, KorRyu3 commented on src/static/index.js
> +}
LLMが回答し始めたら、ユーザーがスクロールに絶対逆らえないから、そこを何とかできるといいね。
個人的に、生成中に過去の会話見るとか結構あるし

2024-02-09 10:05 UTC, KorRyu3 submitted a review, later dismissed
プログラムもデザインも綺麗に動作するので問題ないです。

2024-02-10 13:23 UTC, nka21 commented
approveしたら、そろそろmergeしようかな。

2024-02-10 14:27 UTC, KorRyu3 commented on src/static/index.js
> +  userScrolled = this.scrollTop + this.clientHeight + 1 < this.scrollHeight;
単純な疑問なんだけどさ、この`this`って何を指してるの？
Pythonの`self`とはまた違うものなのかな

2024-02-10 14:36 UTC, KorRyu3 approved these changes
要望通り実装できてるのでベリーグッド！
変数定義が一部 `var` なのが気になるけどまぁ許容範囲内でしょう。
時間がある時にでも直してもらえればokかな

2024-02-10 15:28 UTC, merged

2024-02-10 15:34 UTC, nka21 commented on src/static/index.js
> +  userScrolled = this.scrollTop + this.clientHeight + 1 < this.scrollHeight;
Pythonのselfが理解してないけど、thisはJSに最初から用意されてる変数で、ここではgetElementbyIDで取得したchatBoxの要素を指しているよ

2024-02-10 16:20 UTC, nka21 commented
ミスった、、mergeする前にコード整形すればよかった。
あー、しかもpタグスタイル付け忘れてたし、、、